// This file is automatically generated / configured for Supabase operations.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback to active project URL if env variable is missing or misconfigured
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || 'https://hrxymrrqdgsjvloghmje.supabase.co').replace(/\/$/, '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Normalizes dynamic asset and storage image URLs.
 * Automatically fixes outdated hostnames (e.g. net::ERR_NAME_NOT_RESOLVED) 
 * and handles raw storage filenames or relative paths.
 */
export function getStorageImageUrl(
  pathOrUrl: string | null | undefined,
  bucket: string = 'resource-images',
  defaultFallback: string = '/placeholder.png'
): string {
  if (!pathOrUrl) return defaultFallback;

  // If URL points to an invalid/decommissioned Supabase project domain, rewrite it to current SUPABASE_URL
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) {
    try {
      const urlObj = new URL(pathOrUrl);
      const activeUrlObj = new URL(SUPABASE_URL);

      if (urlObj.hostname !== activeUrlObj.hostname && urlObj.hostname.endsWith('.supabase.co')) {
        urlObj.hostname = activeUrlObj.hostname;
        urlObj.protocol = activeUrlObj.protocol;
        return urlObj.toString();
      }
      return pathOrUrl;
    } catch {
      return defaultFallback;
    }
  }

  // If path is a relative path or filename, construct public storage URL using current client config
  const cleanPath = pathOrUrl.replace(/^\/+/, '');
  return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${cleanPath}`;
}
